Repository plonegovbr/brasil.gov.tiles, pull requests merged in 2018-10, with the labels that each got.

#265 Fix css import warning
  webpack/app/brasilgovtiles.scss
Labels: ready

#208 Remove list tile override
  CHANGES.rst
  src/brasil/gov/tiles/tests/test_upgrades.py
  src/brasil/gov/tiles/tiles/audiogallery.py
  src/brasil/gov/tiles/tiles/list.py
  src/brasil/gov/tiles/tiles/overrides.zcml
  src/brasil/gov/tiles/tiles/templates/audiogallery.pt
  src/brasil/gov/tiles/tiles/templates/list.pt
  src/brasil/gov/tiles/tiles/templates/videogallery.pt
  src/brasil/gov/tiles/tiles/videogallery.py
  src/brasil/gov/tiles/upgrades/__init__.py
  src/brasil/gov/tiles/upgrades/v4100/__init__.py
  src/brasil/gov/tiles/upgrades/v4100/configure.zcml
Labels: 2.x, ready

#207 Remove collection tile override
  CHANGES.rst
  setup.py
  src/brasil/gov/tiles/overrides.zcml
  src/brasil/gov/tiles/testing.py
  src/brasil/gov/tiles/tests/test_collection_tile.py
  src/brasil/gov/tiles/tiles/collection.py
  src/brasil/gov/tiles/tiles/overrides.zcml
  src/brasil/gov/tiles/tiles/templates/collection.pt
Labels: 2.x, help wanted, in progress

#264 Update webpack config
  .gitignore
  CHANGES.rst
  buildout.cfg
  src/brasil/gov/tiles/browser/__init__.py
  src/brasil/gov/tiles/browser/configure.zcml
  src/brasil/gov/tiles/browser/static/README.rst
  src/brasil/gov/tiles/configure.zcml
  src/brasil/gov/tiles/profiles/default/cssregistry.xml
  src/brasil/gov/tiles/profiles/default/jsregistry.xml
  src/brasil/gov/tiles/profiles/default/metadata.xml
  src/brasil/gov/tiles/tests/test_resources_viewlet.py
  src/brasil/gov/tiles/tests/test_upgrades.py
  src/brasil/gov/tiles/upgrades/configure.zcml
  src/brasil/gov/tiles/upgrades/v4101/__init__.py
  src/brasil/gov/tiles/upgrades/v4101/configure.zcml
  webpack/app/img/footer-arrow.jpg
  webpack/app/img/footer-arrow_jpg.png
  webpack/app/img/jplayer.blue.monday.jpg
  webpack/app/img/jplayer.blue.monday.png
  webpack/app/resources.pt
  webpack/app/scss/tiles/_audio.scss
  webpack/app/scss/tiles/_videogallery.scss
  webpack/package.json
  webpack/postcss.config.js
  webpack/webpack.config.js
Labels: ready
