Repository plonegovbr/brasil.gov.tiles, pull requests merged in 2018-08, with the labels that each got.

#209 Remove NITF tile override
  CHANGES.rst
  src/brasil/gov/tiles/profiles.zcml
  src/brasil/gov/tiles/profiles/default/registry.xml
  src/brasil/gov/tiles/profiles/testfixture/registry.xml
  src/brasil/gov/tiles/tests/test_nitf_tile.py
  src/brasil/gov/tiles/tests/test_setup.py
  src/brasil/gov/tiles/tests/test_upgrades.py
  src/brasil/gov/tiles/tiles/configure.zcml
  src/brasil/gov/tiles/tiles/nitf.py
  src/brasil/gov/tiles/tiles/templates/nitf.pt
  src/brasil/gov/tiles/upgrades/__init__.py
  src/brasil/gov/tiles/upgrades/v4100/__init__.py
  src/brasil/gov/tiles/upgrades/v4100/configure.zcml
  webpack/app/scss/_layout.scss
Labels: 2.x, help wanted, in progress

#205 Remove banner tile override
  CHANGES.rst
  src/brasil/gov/tiles/tests/test_banner.py
  src/brasil/gov/tiles/tests/test_upgrades.py
  src/brasil/gov/tiles/tiles/banner.py
  src/brasil/gov/tiles/tiles/overrides.zcml
  src/brasil/gov/tiles/tiles/templates/banner.pt
  src/brasil/gov/tiles/upgrades/v4100/__init__.py
  src/brasil/gov/tiles/upgrades/v4100/configure.zcml
Labels: 2.x, help wanted, ready

#230 Update CI configuration
  .travis.yml
  buildout.cfg
Labels: 2.x, in progress

#228 Add carouselvideos tile
  CHANGES.rst
  README.rst
  docs/videocarousel.png
  setup.py
  src/brasil/gov/tiles/configure.zcml
  src/brasil/gov/tiles/profiles/default/metadata.xml
  src/brasil/gov/tiles/profiles/default/registry.xml
  src/brasil/gov/tiles/testing.py
  src/brasil/gov/tiles/tests/test_upgrades.py
  src/brasil/gov/tiles/tests/test_videocarousel.py
  src/brasil/gov/tiles/tiles/configure.zcml
  src/brasil/gov/tiles/tiles/templates/videocarousel.pt
  src/brasil/gov/tiles/tiles/videocarousel.py
  src/brasil/gov/tiles/upgrades/v4100/__init__.py
  src/brasil/gov/tiles/upgrades/v4100/configure.zcml
  webpack/app/brasilgovtiles.js
  webpack/app/brasilgovtiles.scss
  webpack/app/js/tiles/videocarousel.js
  webpack/app/js/youtube.js
  webpack/app/scss/tiles/_videocarousel.scss
Labels: 2.x, ready

#210 Remove embed tile override
  CHANGES.rst
  src/brasil/gov/tiles/tiles/embed.py
  src/brasil/gov/tiles/tiles/overrides.zcml
  src/brasil/gov/tiles/tiles/templates/embed.pt
Labels: 2.x, help wanted, ready

#235 Add group carousel tile
  CHANGES.rst
  README.rst
  docs/groupcarousel.png
  src/brasil/gov/tiles/locales/brasil.gov.tiles.pot
  src/brasil/gov/tiles/locales/pt_BR/LC_MESSAGES/brasil.gov.tiles.po
  src/brasil/gov/tiles/profiles/default/registry.xml
  src/brasil/gov/tiles/tests/test_groupcarousel_tile.py
  src/brasil/gov/tiles/tiles/configure.zcml
  src/brasil/gov/tiles/tiles/groupcarousel.py
  src/brasil/gov/tiles/tiles/templates/groupcarousel.pt
  src/brasil/gov/tiles/upgrades/v4100/__init__.py
  webpack/app/brasilgovtiles.js
  webpack/app/brasilgovtiles.scss
  webpack/app/img/icon-carosel.png
  webpack/app/js/tiles/groupcarousel.js
  webpack/app/scss/tiles/_groupcarousel.scss
Labels: 2.x, ready

#236 Remove Em destaque tile
  CHANGES.rst
  src/brasil/gov/tiles/profiles/default/registry.xml
  src/brasil/gov/tiles/profiles/testfixture/registry.xml
  src/brasil/gov/tiles/tests/test_setup.py
  src/brasil/gov/tiles/tests/test_upgrades.py
  src/brasil/gov/tiles/tiles/configure.zcml
  src/brasil/gov/tiles/tiles/em_destaque.py
  src/brasil/gov/tiles/tiles/templates/em_destaque.pt
  src/brasil/gov/tiles/upgrades/__init__.py
  src/brasil/gov/tiles/upgrades/v4100/__init__.py
  src/brasil/gov/tiles/upgrades/v4100/configure.zcml
  webpack/app/scss/_layout.scss
Labels: 2.x, ready

#237 Remove Social tile
  CHANGES.rst
  src/brasil/gov/tiles/profiles/default/registry.xml
  src/brasil/gov/tiles/profiles/testfixture/registry.xml
  src/brasil/gov/tiles/tests/test_setup.py
  src/brasil/gov/tiles/tests/test_social.py
  src/brasil/gov/tiles/tiles/configure.zcml
  src/brasil/gov/tiles/tiles/social.py
  src/brasil/gov/tiles/tiles/templates/social.pt
  src/brasil/gov/tiles/upgrades/v4100/__init__.py
  webpack/app/brasilgovtiles.scss
  webpack/app/scss/_layout.scss
  webpack/app/scss/tiles/_social.scss
Labels: 2.x, ready

#239 Remove Banner rotativo tile
  CHANGES.rst
  setup.py
  src/brasil/gov/tiles/configure.zcml
  src/brasil/gov/tiles/patches_banner_rotativo.py
  src/brasil/gov/tiles/profiles/default/registry.xml
  src/brasil/gov/tiles/profiles/testfixture/registry.xml
  src/brasil/gov/tiles/tests/test_bannerrotativo_tile.py
  src/brasil/gov/tiles/tests/test_setup.py
  src/brasil/gov/tiles/tiles/banner_rotativo.py
  src/brasil/gov/tiles/tiles/configure.zcml
  src/brasil/gov/tiles/tiles/templates/banner_rotativo.pt
  src/brasil/gov/tiles/upgrades/v4100/__init__.py
  webpack/app/brasilgovtiles.js
  webpack/app/brasilgovtiles.scss
  webpack/app/js/tiles/banner_rotativo.js
  webpack/app/scss/_layout.scss
  webpack/app/scss/tiles/_banner_rotativo.scss
Labels: 2.x, ready

#206 Remove basic tile override
  CHANGES.rst
  src/brasil/gov/tiles/tests/test_basic.py
  src/brasil/gov/tiles/tests/test_upgrades.py
  src/brasil/gov/tiles/tiles/basic.py
  src/brasil/gov/tiles/tiles/overrides.zcml
  src/brasil/gov/tiles/tiles/templates/basic.pt
  src/brasil/gov/tiles/upgrades/v4100/__init__.py
  src/brasil/gov/tiles/upgrades/v4100/configure.zcml
Labels: 2.x, help wanted, ready

#243 Remove Destaque tile
  CHANGES.rst
  src/brasil/gov/tiles/profiles/default/registry.xml
  src/brasil/gov/tiles/profiles/testfixture/registry.xml
  src/brasil/gov/tiles/tests/test_destaque_tile.py
  src/brasil/gov/tiles/tests/test_setup.py
  src/brasil/gov/tiles/tiles/configure.zcml
  src/brasil/gov/tiles/tiles/destaque.py
  src/brasil/gov/tiles/tiles/templates/destaque.pt
  src/brasil/gov/tiles/upgrades/v4100/__init__.py
  webpack/app/brasilgovtiles.scss
  webpack/app/scss/_layout.scss
  webpack/app/scss/tiles/_destaque.scss
Labels: 2.x, ready

#244 Fix test
  src/brasil/gov/tiles/tests/test_setup.py
Labels: 2.x, ready

#232 Swiper in webpack
  buildout.cfg
  src/brasil/gov/tiles/profiles/default/cssregistry.xml
  src/brasil/gov/tiles/profiles/default/jsregistry.xml
  src/brasil/gov/tiles/tests/test_upgrades.py
  webpack/.babelrc
  webpack/.gitignore
  webpack/app/brasilgovtiles.scss
  webpack/app/js/tiles/groupcarousel.js
  webpack/app/js/tiles/highlightscarousel.js
  webpack/app/js/tiles/photogallery.js
  webpack/app/js/tiles/videocarousel.js
  webpack/app/vendor/swiper.min.css
  webpack/app/vendor/swiper.min.js
  webpack/package.json
Labels: 2.x, ready

#246 Update package documentation
  README.rst
Labels: 2.x, ready

#247 Add Tiles Share Functionality
  CHANGES.rst
  README.rst
  docs/tileshare.png
  src/brasil/gov/tiles/browser/__init__.py
  src/brasil/gov/tiles/browser/configure.zcml
  src/brasil/gov/tiles/browser/tileshare.pt
  src/brasil/gov/tiles/browser/tileshare.py
  src/brasil/gov/tiles/configure.zcml
  webpack/app/brasilgovtiles.js
  webpack/app/brasilgovtiles.scss
  webpack/app/js/tileshare.js
  webpack/app/scss/_tileshare.scss
  webpack/app/sprite/fb-ic.png
  webpack/app/sprite/gplus-ic.png
  webpack/app/sprite/link-ic.png
  webpack/app/sprite/linkedin-ic.png
  webpack/app/sprite/twitter-ic.png
  webpack/package.json
Labels: 2.x, ready
